--
-- PostgreSQL database dump
--

\restrict 8kO164koPtVPXnizr0JIYay4I7qUacWMu0l9tAiDZOnnr1q2Ds6XWKE6FXRcwW1

-- Dumped from database version 18.0 (Debian 18.0-1.pgdg13+3)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: ecommerce; Type: SCHEMA; Schema: -; Owner: ecommerce
--

CREATE SCHEMA ecommerce;


ALTER SCHEMA ecommerce OWNER TO ecommerce;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: ecommerce; Owner: ecommerce
--

CREATE TABLE ecommerce.categories (
    id uuid NOT NULL,
    name text NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE ecommerce.categories OWNER TO ecommerce;

--
-- Name: category_children; Type: TABLE; Schema: ecommerce; Owner: ecommerce
--

CREATE TABLE ecommerce.category_children (
    parent_id uuid NOT NULL,
    child_id uuid NOT NULL
);


ALTER TABLE ecommerce.category_children OWNER TO ecommerce;

--
-- Name: cms; Type: TABLE; Schema: ecommerce; Owner: ecommerce
--

CREATE TABLE ecommerce.cms (
    id uuid NOT NULL,
    code text NOT NULL,
    value text NOT NULL,
    language character varying(5) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE ecommerce.cms OWNER TO ecommerce;

--
-- Name: goose_migrations; Type: TABLE; Schema: ecommerce; Owner: ecommerce
--

CREATE TABLE ecommerce.goose_migrations (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE ecommerce.goose_migrations OWNER TO ecommerce;

--
-- Name: goose_migrations_id_seq; Type: SEQUENCE; Schema: ecommerce; Owner: ecommerce
--

ALTER TABLE ecommerce.goose_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ecommerce.goose_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: ecommerce; Owner: ecommerce
--

CREATE TABLE ecommerce.products (
    id uuid NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    brand character varying(50) NOT NULL,
    code character varying(50) NOT NULL,
    price integer DEFAULT 0,
    stock integer DEFAULT 0,
    image_url text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    category_id uuid
);


ALTER TABLE ecommerce.products OWNER TO ecommerce;

--
-- Name: shopping_basket; Type: TABLE; Schema: ecommerce; Owner: ecommerce
--

CREATE TABLE ecommerce.shopping_basket (
    id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE ecommerce.shopping_basket OWNER TO ecommerce;

--
-- Name: shopping_basket_items; Type: TABLE; Schema: ecommerce; Owner: ecommerce
--

CREATE TABLE ecommerce.shopping_basket_items (
    shopping_basket_id uuid,
    product_id uuid
);


ALTER TABLE ecommerce.shopping_basket_items OWNER TO ecommerce;

--
-- Data for Name: categories; Type: TABLE DATA; Schema: ecommerce; Owner: ecommerce
--

INSERT INTO ecommerce.categories (id, name, created_at, updated_at) VALUES ('7f3b0c1a-c91d-47ca-a087-a54194808715', 'GPU', '2025-11-27 17:26:49.908433', '2025-11-27 17:26:49.908433');
INSERT INTO ecommerce.categories (id, name, created_at, updated_at) VALUES ('ac64de74-606e-42e9-ba3a-795344d89e37', 'ROOT', '2025-11-27 17:38:24.746776', '2025-11-27 17:38:27.353038');


--
-- Data for Name: category_children; Type: TABLE DATA; Schema: ecommerce; Owner: ecommerce
--

INSERT INTO ecommerce.category_children (parent_id, child_id) VALUES ('ac64de74-606e-42e9-ba3a-795344d89e37', '7f3b0c1a-c91d-47ca-a087-a54194808715');


--
-- Data for Name: cms; Type: TABLE DATA; Schema: ecommerce; Owner: ecommerce
--

INSERT INTO ecommerce.cms (id, code, value, language, created_at, updated_at) VALUES ('cf229587-7d6d-4f98-9635-70518633a1ef', '90YV0L71_M0NA00_DESCRIPTION', 'De ASUS Prime Radeon RX 9070 XT Gaming OC 16GB Videokaart is een krachtige AMD-kaart die is uitgerust met 16 GB GDDR6-videogeheugen en een GPU-kloksnelheid van tot wel 3030 MHz. Met 4096 stream processors biedt deze videokaart uitstekende prestaties voor zowel gaming als professionele toepassingen. De ASUS Prime-serie is ontworpen voor gamers en enthousiastelingen die op zoek zijn naar een betrouwbare en geavanceerde grafische oplossing.', 'nl_BE', '2025-11-27 17:44:22.527961', '2025-11-27 17:44:22.527961');
INSERT INTO ecommerce.cms (id, code, value, language, created_at, updated_at) VALUES ('b808c604-a460-4674-9cf3-bf8ce2d54209', '90YV0L71_M0NA00_NAME', 'MSI Prime Radeon RX 9070 XT 16GB OC Videokaart', 'nl_BE', '2025-11-27 17:44:25.432456', '2025-11-27 17:44:25.432456');


--
-- Data for Name: goose_migrations; Type: TABLE DATA; Schema: ecommerce; Owner: ecommerce
--

INSERT INTO ecommerce.goose_migrations (id, version_id, is_applied, tstamp) VALUES (1, 0, true, '2025-11-27 16:20:29.689847');
INSERT INTO ecommerce.goose_migrations (id, version_id, is_applied, tstamp) VALUES (2, 20251123191812, true, '2025-11-27 16:20:29.699769');
INSERT INTO ecommerce.goose_migrations (id, version_id, is_applied, tstamp) VALUES (3, 20251123213915, true, '2025-11-27 16:20:29.705473');
INSERT INTO ecommerce.goose_migrations (id, version_id, is_applied, tstamp) VALUES (4, 20251124204204, true, '2025-11-27 16:20:29.712651');
INSERT INTO ecommerce.goose_migrations (id, version_id, is_applied, tstamp) VALUES (5, 20251125211957, true, '2025-11-27 16:20:29.717002');
INSERT INTO ecommerce.goose_migrations (id, version_id, is_applied, tstamp) VALUES (6, 20251127180713, true, '2025-11-27 18:10:18.18639');


--
-- Data for Name: products; Type: TABLE DATA; Schema: ecommerce; Owner: ecommerce
--

INSERT INTO ecommerce.products (id, name, description, brand, code, price, stock, image_url, created_at, updated_at, category_id) VALUES ('e9eddf9d-d849-4d14-9d23-d3013c7c6956', '90YV0L71_M0NA00_NAME', '90YV0L71_M0NA00_DESCRIPTION', 'ASUS', '90YV0L71-M0NA00', 669, 0, 'https://www.megekko.nl/productimg/1699548/nw/1_ASUS-Prime-Radeon-RX-9070-XT-16GB-OC-Videokaart.jpg', '2025-11-27 17:42:38.47312', '2025-11-27 17:42:38.47312', '7f3b0c1a-c91d-47ca-a087-a54194808715');


--
-- Data for Name: shopping_basket; Type: TABLE DATA; Schema: ecommerce; Owner: ecommerce
--



--
-- Data for Name: shopping_basket_items; Type: TABLE DATA; Schema: ecommerce; Owner: ecommerce
--



--
-- Name: goose_migrations_id_seq; Type: SEQUENCE SET; Schema: ecommerce; Owner: ecommerce
--

SELECT pg_catalog.setval('ecommerce.goose_migrations_id_seq', 6, true);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce
--

ALTER TABLE ONLY ecommerce.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: category_children category_children_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce
--

ALTER TABLE ONLY ecommerce.category_children
    ADD CONSTRAINT category_children_pkey PRIMARY KEY (parent_id, child_id);


--
-- Name: cms cms_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce
--

ALTER TABLE ONLY ecommerce.cms
    ADD CONSTRAINT cms_pkey PRIMARY KEY (id);


--
-- Name: goose_migrations goose_migrations_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce
--

ALTER TABLE ONLY ecommerce.goose_migrations
    ADD CONSTRAINT goose_migrations_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce
--

ALTER TABLE ONLY ecommerce.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: shopping_basket shopping_basket_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce
--

ALTER TABLE ONLY ecommerce.shopping_basket
    ADD CONSTRAINT shopping_basket_pkey PRIMARY KEY (id);


--
-- Name: category_children category_children_child_id_fkey; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce
--

ALTER TABLE ONLY ecommerce.category_children
    ADD CONSTRAINT category_children_child_id_fkey FOREIGN KEY (child_id) REFERENCES ecommerce.categories(id) ON DELETE CASCADE;


--
-- Name: category_children category_children_parent_id_fkey; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce
--

ALTER TABLE ONLY ecommerce.category_children
    ADD CONSTRAINT category_children_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES ecommerce.categories(id) ON DELETE CASCADE;


--
-- Name: products products_category_id_fkey; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce
--

ALTER TABLE ONLY ecommerce.products
    ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES ecommerce.categories(id);


--
-- Name: shopping_basket_items shopping_basket_items_product_id_fkey; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce
--

ALTER TABLE ONLY ecommerce.shopping_basket_items
    ADD CONSTRAINT shopping_basket_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES ecommerce.products(id);


--
-- Name: shopping_basket_items shopping_basket_items_shopping_basket_id_fkey; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce
--

ALTER TABLE ONLY ecommerce.shopping_basket_items
    ADD CONSTRAINT shopping_basket_items_shopping_basket_id_fkey FOREIGN KEY (shopping_basket_id) REFERENCES ecommerce.shopping_basket(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 8kO164koPtVPXnizr0JIYay4I7qUacWMu0l9tAiDZOnnr1q2Ds6XWKE6FXRcwW1

