-- +goose Up
CREATE TABLE ECOMMERCE.RESERVATIONS
(
    SHOPPING_BASKET_ID UUID NOT NULL REFERENCES ECOMMERCE.SHOPPING_BASKET (ID),
    PRODUCT_ID         UUID NOT NULL REFERENCES ECOMMERCE.PRODUCTS (ID),
    QUANTITY           INTEGER DEFAULT 0
);
-- +goose Down
DROP TABLE ECOMMERCE.RESERVATIONS;
